# Projeto - Prevendo Nível de Satisfação de Clientes - Victor Tintel

In [3]:
#Importando pacotes que serão utilizados no projeto

import pandas as pd
from sklearn.decomposition import PCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

In [5]:
# Carregando os dados

dados = pd.read_csv('dadoshistoricos.csv')

In [7]:
# Avaliando o tipo de objeto

type(dados)

pandas.core.frame.DataFrame

In [ ]:
# Removendo a coluna ID
# axis=1 é pq queremos excluir a coluna inteira.

dados = dados.drop('ID', axis=1)
dados.shape

In [11]:
#Exibindo os dados

dados.head()

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [15]:
# Separando a variavel TARGET

TARGET = dados[['TARGET']]

In [63]:
# Criando uma lista com as colunas do objeto
# até 369 porque vamos deixa a variavel target de fora.

colunas = dados.columns[0:369].tolist()

In [19]:
# Visualizando a lista com os nomes das colunas

colunas

['var3',
 'var15',
 'imp_ent_var16_ult1',
 'imp_op_var39_comer_ult1',
 'imp_op_var39_comer_ult3',
 'imp_op_var40_comer_ult1',
 'imp_op_var40_comer_ult3',
 'imp_op_var40_efect_ult1',
 'imp_op_var40_efect_ult3',
 'imp_op_var40_ult1',
 'imp_op_var41_comer_ult1',
 'imp_op_var41_comer_ult3',
 'imp_op_var41_efect_ult1',
 'imp_op_var41_efect_ult3',
 'imp_op_var41_ult1',
 'imp_op_var39_efect_ult1',
 'imp_op_var39_efect_ult3',
 'imp_op_var39_ult1',
 'imp_sal_var16_ult1',
 'ind_var1_0',
 'ind_var1',
 'ind_var2_0',
 'ind_var2',
 'ind_var5_0',
 'ind_var5',
 'ind_var6_0',
 'ind_var6',
 'ind_var8_0',
 'ind_var8',
 'ind_var12_0',
 'ind_var12',
 'ind_var13_0',
 'ind_var13_corto_0',
 'ind_var13_corto',
 'ind_var13_largo_0',
 'ind_var13_largo',
 'ind_var13_medio_0',
 'ind_var13_medio',
 'ind_var13',
 'ind_var14_0',
 'ind_var14',
 'ind_var17_0',
 'ind_var17',
 'ind_var18_0',
 'ind_var18',
 'ind_var19',
 'ind_var20_0',
 'ind_var20',
 'ind_var24_0',
 'ind_var24',
 'ind_var25_cte',
 'ind_var26_0',
 'ind_var26_cte',
 'ind_var26',
 'ind_var25_0',
 'ind_var25',
 'ind_var27_0',
 'ind_var28_0',
 'ind_var28',
 'ind_var27',
 'ind_var29_0',
 'ind_var29',
 'ind_var30_0',
 'ind_var30',
 'ind_var31_0',
 'ind_var31',
 'ind_var32_cte',
 'ind_var32_0',
 'ind_var32',
 'ind_var33_0',
 'ind_var33',
 'ind_var34_0',
 'ind_var34',
 'ind_var37_cte',
 'ind_var37_0',
 'ind_var37',
 'ind_var39_0',
 'ind_var40_0',
 'ind_var40',
 'ind_var41_0',
 'ind_var41',
 'ind_var39',
 'ind_var44_0',
 'ind_var44',
 'ind_var46_0',
 'ind_var46',
 'num_var1_0',
 'num_var1',
 'num_var4',
 'num_var5_0',
 'num_var5',
 'num_var6_0',
 'num_var6',
 'num_var8_0',
 'num_var8',
 'num_var12_0',
 'num_var12',
 'num_var13_0',
 'num_var13_corto_0',
 'num_var13_corto',
 'num_var13_largo_0',
 'num_var13_largo',
 'num_var13_medio_0',
 'num_var13_medio',
 'num_var13',
 'num_var14_0',
 'num_var14',
 'num_var17_0',
 'num_var17',
 'num_var18_0',
 'num_var18',
 'num_var20_0',
 'num_var20',
 'num_var24_0',
 'num_var24',
 'num_var26_0',
 'num_var26',
 'num_var25_0',
 'num_var25',
 'num_op_var40_hace2',
 'num_op_var40_hace3',
 'num_op_var40_ult1',
 'num_op_var40_ult3',
 'num_op_var41_hace2',
 'num_op_var41_hace3',
 'num_op_var41_ult1',
 'num_op_var41_ult3',
 'num_op_var39_hace2',
 'num_op_var39_hace3',
 'num_op_var39_ult1',
 'num_op_var39_ult3',
 'num_var27_0',
 'num_var28_0',
 'num_var28',
 'num_var27',
 'num_var29_0',
 'num_var29',
 'num_var30_0',
 'num_var30',
 'num_var31_0',
 'num_var31',
 'num_var32_0',
 'num_var32',
 'num_var33_0',
 'num_var33',
 'num_var34_0',
 'num_var34',
 'num_var35',
 'num_var37_med_ult2',
 'num_var37_0',
 'num_var37',
 'num_var39_0',
 'num_var40_0',
 'num_var40',
 'num_var41_0',
 'num_var41',
 'num_var39',
 'num_var42_0',
 'num_var42',
 'num_var44_0',
 'num_var44',
 'num_var46_0',
 'num_var46',
 'saldo_var1',
 'saldo_var5',
 'saldo_var6',
 'saldo_var8',
 'saldo_var12',
 'saldo_var13_corto',
 'saldo_var13_largo',
 'saldo_var13_medio',
 'saldo_var13',
 'saldo_var14',
 'saldo_var17',
 'saldo_var18',
 'saldo_var20',
 'saldo_var24',
 'saldo_var26',
 'saldo_var25',
 'saldo_var28',
 'saldo_var27',
 'saldo_var29',
 'saldo_var30',
 'saldo_var31',
 'saldo_var32',
 'saldo_var33',
 'saldo_var34',
 'saldo_var37',
 'saldo_var40',
 'saldo_var41',
 'saldo_var42',
 'saldo_var44',
 'saldo_var46',
 'var36',
 'delta_imp_amort_var18_1y3',
 'delta_imp_amort_var34_1y3',
 'delta_imp_aport_var13_1y3',
 'delta_imp_aport_var17_1y3',
 'delta_imp_aport_var33_1y3',
 'delta_imp_compra_var44_1y3',
 'delta_imp_reemb_var13_1y3',
 'delta_imp_reemb_var17_1y3',
 'delta_imp_reemb_var33_1y3',
 'delta_imp_trasp_var17_in_1y3',
 'delta_imp_trasp_var17_out_1y3',
 'delta_imp_trasp_var33_in_1y3',
 'delta_imp_trasp_var33_out_1y3',
 'delta_imp_venta_var44_1y3',
 'delta_num_aport_var13_1y3',
 'delta_num_aport_var17_1y3',
 'delta_num_aport_var33_1y3',
 'delta_num_compra_var44_1y3',
 'delta_num_reemb_var13_1y3',
 'delta_num_reemb_var17_1y3',
 'delta_num_reemb_var33_1y3',
 'delta_num_trasp_var17_in_1y3',
 'delta_num_trasp_var17_out_1y3',
 'delta_num_trasp_var33_in_1y3',
 'delta_num_trasp_var33_out_1y3',
 'delta_num_venta_var44_1y3',
 'imp_amort_var18_hace3',
 'imp_amort_var18_ult1',
 'imp_amort_var34_hace3',
 'imp_amort_var34_ult1',
 'imp_aport_var13_hace3',
 'imp_aport_var13_ult1',
 'imp_aport_var17_hace3',
 'imp_aport_var17_ult1',
 'imp_aport_var33_hace3',
 'imp_aport_var33_ult1',
 'imp_var7_emit_ult1',
 'imp_var7_recib_ult1',
 'imp_compra_var44_hace3',
 'imp_compra_var44_ult1',
 'imp_reemb_var13_hace3',
 'imp_reemb_var13_ult1',
 'imp_reemb_var17_hace3',
 'imp_reemb_var17_ult1',
 'imp_reemb_var33_hace3',
 'imp_reemb_var33_ult1',
 'imp_var43_emit_ult1',
 'imp_trans_var37_ult1',
 'imp_trasp_var17_in_hace3',
 'imp_trasp_var17_in_ult1',
 'imp_trasp_var17_out_hace3',
 'imp_trasp_var17_out_ult1',
 'imp_trasp_var33_in_hace3',
 'imp_trasp_var33_in_ult1',
 'imp_trasp_var33_out_hace3',
 'imp_trasp_var33_out_ult1',
 'imp_venta_var44_hace3',
 'imp_venta_var44_ult1',
 'ind_var7_emit_ult1',
 'ind_var7_recib_ult1',
 'ind_var10_ult1',
 'ind_var10cte_ult1',
 'ind_var9_cte_ult1',
 'ind_var9_ult1',
 'ind_var43_emit_ult1',
 'ind_var43_recib_ult1',
 'var21',
 'num_var2_0_ult1',
 'num_var2_ult1',
 'num_aport_var13_hace3',
 'num_aport_var13_ult1',
 'num_aport_var17_hace3',
 'num_aport_var17_ult1',
 'num_aport_var33_hace3',
 'num_aport_var33_ult1',
 'num_var7_emit_ult1',
 'num_var7_recib_ult1',
 'num_compra_var44_hace3',
 'num_compra_var44_ult1',
 'num_ent_var16_ult1',
 'num_var22_hace2',
 'num_var22_hace3',
 'num_var22_ult1',
 'num_var22_ult3',
 'num_med_var22_ult3',
 'num_med_var45_ult3',
 'num_meses_var5_ult3',
 'num_meses_var8_ult3',
 'num_meses_var12_ult3',
 'num_meses_var13_corto_ult3',
 'num_meses_var13_largo_ult3',
 'num_meses_var13_medio_ult3',
 'num_meses_var17_ult3',
 'num_meses_var29_ult3',
 'num_meses_var33_ult3',
 'num_meses_var39_vig_ult3',
 'num_meses_var44_ult3',
 'num_op_var39_comer_ult1',
 'num_op_var39_comer_ult3',
 'num_op_var40_comer_ult1',
 'num_op_var40_comer_ult3',
 'num_op_var40_efect_ult1',
 'num_op_var40_efect_ult3',
 'num_op_var41_comer_ult1',
 'num_op_var41_comer_ult3',
 'num_op_var41_efect_ult1',
 'num_op_var41_efect_ult3',
 'num_op_var39_efect_ult1',
 'num_op_var39_efect_ult3',
 'num_reemb_var13_hace3',
 'num_reemb_var13_ult1',
 'num_reemb_var17_hace3',
 'num_reemb_var17_ult1',
 'num_reemb_var33_hace3',
 'num_reemb_var33_ult1',
 'num_sal_var16_ult1',
 'num_var43_emit_ult1',
 'num_var43_recib_ult1',
 'num_trasp_var11_ult1',
 'num_trasp_var17_in_hace3',
 'num_trasp_var17_in_ult1',
 'num_trasp_var17_out_hace3',
 'num_trasp_var17_out_ult1',
 'num_trasp_var33_in_hace3',
 'num_trasp_var33_in_ult1',
 'num_trasp_var33_out_hace3',
 'num_trasp_var33_out_ult1',
 'num_venta_var44_hace3',
 'num_venta_var44_ult1',
 'num_var45_hace2',
 'num_var45_hace3',
 'num_var45_ult1',
 'num_var45_ult3',
 'saldo_var2_ult1',
 'saldo_medio_var5_hace2',
 'saldo_medio_var5_hace3',
 'saldo_medio_var5_ult1',
 'saldo_medio_var5_ult3',
 'saldo_medio_var8_hace2',
 'saldo_medio_var8_hace3',
 'saldo_medio_var8_ult1',
 'saldo_medio_var8_ult3',
 'saldo_medio_var12_hace2',
 'saldo_medio_var12_hace3',
 'saldo_medio_var12_ult1',
 'saldo_medio_var12_ult3',
 'saldo_medio_var13_corto_hace2',
 'saldo_medio_var13_corto_hace3',
 'saldo_medio_var13_corto_ult1',
 'saldo_medio_var13_corto_ult3',
 'saldo_medio_var13_largo_hace2',
 'saldo_medio_var13_largo_hace3',
 'saldo_medio_var13_largo_ult1',
 'saldo_medio_var13_largo_ult3',
 'saldo_medio_var13_medio_hace2',
 'saldo_medio_var13_medio_hace3',
 'saldo_medio_var13_medio_ult1',
 'saldo_medio_var13_medio_ult3',
 'saldo_medio_var17_hace2',
 'saldo_medio_var17_hace3',
 'saldo_medio_var17_ult1',
 'saldo_medio_var17_ult3',
 'saldo_medio_var29_hace2',
 'saldo_medio_var29_hace3',
 'saldo_medio_var29_ult1',
 'saldo_medio_var29_ult3',
 'saldo_medio_var33_hace2',
 'saldo_medio_var33_hace3',
 'saldo_medio_var33_ult1',
 'saldo_medio_var33_ult3',
 'saldo_medio_var44_hace2',
 'saldo_medio_var44_hace3',
 'saldo_medio_var44_ult1',
 'saldo_medio_var44_ult3',
 'var38']

In [69]:
# Criando um array dos dados
# Aqui nós só vamos pegar os valores

array = dados.values

In [71]:
# Visualizando o tipo do objeto

type(array)

numpy.ndarray

In [73]:
array

array([[-1.27454171e+00, -3.75971524e-01,  5.68290715e-02, ...,
         7.14085061e-03, -1.37047594e-03,  0.00000000e+00],
       [-1.08037716e-01,  4.88622845e-02,  1.79918952e+00, ...,
         2.49926469e-03, -6.12720653e-02,  0.00000000e+00],
       [ 2.79354915e-02,  4.39468380e-01, -3.35929635e-01, ...,
        -2.75700515e-03,  1.03078173e-03,  0.00000000e+00],
       ...,
       [-1.06215783e-01,  3.47586595e-01, -2.95097577e-01, ...,
         7.01464933e-03,  2.31070613e-03,  0.00000000e+00],
       [ 4.85721124e-02,  4.31814156e-01, -2.95902111e-01, ...,
        -2.45769295e-03, -4.37183127e-03,  0.00000000e+00],
       [-1.27067838e+00, -3.83891099e-01,  7.62670049e-02, ...,
        -9.70063671e-03, -1.01148052e-02,  0.00000000e+00]])

In [27]:
# Separando o array em componentes de input (X) da variavel TARGET
X = array[:,0:369]


# Gerando a nova escala (normalizando os dados)
scaler = MinMaxScaler(feature_range = (0, 1))
rescaledX = scaler.fit_transform(X)

In [31]:
# Transformando o Array em Dataframe

dadosNormalizados = pd.DataFrame(rescaledX, columns = colunas)

In [33]:
# Visualizando o formato do dataframe

dadosNormalizados.shape

(76020, 369)

In [35]:
dadosNormalizados.head()

,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,imp_op_var40_ult1,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,0.999764,0.18,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001545
1,0.999764,0.29,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002003
2,0.999764,0.18,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002822
3,0.999764,0.32,0.0,0.01513,0.009275,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.002671
4,0.999764,0.34,0.0,0.00000,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.005091

In [77]:
# Reduzindo a dimensionalidade
# aqui vamos reduzir nosso DF para 30 colunas.
# Não vai perder informações, apenas compacta-las

pca = PCA(n_components = 30) 
dados = pca.fit_transform(dadosNormalizados)

In [39]:
# Convertendo o objeto PCA para um dataframe

dados = pd.DataFrame(dados)

In [41]:
dados.head(10)

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,-1.274542,-0.375972,0.056829,0.439875,-0.039916,-0.114012,-0.054436,-0.033986,-0.000646,0.010634,...,-0.018053,-0.024860,-0.006067,0.001798,0.007291,0.010016,0.005148,0.003657,0.007141,-0.001370
1,-0.108038,0.048862,1.799190,-0.203618,-1.327840,0.274607,-0.164000,-0.164823,-0.081474,0.063830,...,0.319753,-0.003157,0.044331,0.056909,-0.159439,-0.504883,-0.047619,-0.008906,0.002499,-0.061272
2,0.027935,0.439468,-0.335930,0.187874,-0.066789,0.081755,0.507333,0.414996,-0.005015,0.008462,...,0.009034,0.007580,-0.040357,-0.002682,-0.011075,-0.002493,-0.029984,-0.005791,-0.002757,0.001031
3,1.427146,-1.492291,-0.688243,-0.024221,-0.671363,-0.843693,0.315254,-0.564295,-0.147847,0.076420,...,-0.042550,-0.024843,-0.007111,0.037683,-0.060107,0.012919,0.002226,0.009852,0.023860,0.053124
4,0.426464,-0.122872,1.311621,-0.190963,1.681094,-0.904324,-0.185651,0.363184,0.333842,0.352784,...,0.313539,-0.216911,-0.019962,-0.105300,0.035171,-0.034816,-0.123019,-0.030567,-0.023965,-0.146107
5,-1.274542,-0.375972,0.056830,0.439875,-0.039916,-0.114013,-0.054436,-0.033986,-0.000647,0.010632,...,-0.018054,-0.024860,-0.006069,0.001796,0.007291,0.010019,0.005147,0.003657,0.007141,-0.001372
6,0.460814,0.517974,-0.113759,0.159073,0.044277,0.160775,-0.051590,-0.216157,0.011502,0.000049,...,0.000052,-0.020922,0.017515,0.014474,0.021940,0.000121,-0.002179,-0.001417,-0.002762,-0.010593
7,0.310483,0.434306,-0.110227,0.030609,0.047570,0.149564,-0.105995,-0.227403,-0.041892,0.000088,...,-0.037921,-0.019973,-0.021006,0.009812,0.003067,-0.002886,-0.030542,-0.005521,0.005989,-0.004353
8,-1.270846,-0.383547,0.075422,0.434967,-0.040744,-0.121680,-0.058916,-0.033256,0.000001,0.000258,...,0.013159,0.040022,0.025770,0.008808,0.014365,-0.006134,0.035092,0.005216,-0.008968,-0.009734
9,0.054788,0.451611,-0.461396,-1.325357,0.011844,0.113456,-0.098462,-0.181546,-0.011425,0.008626,...,-0.002976,-0.051471,0.026457,0.007508,0.001020,0.004211,-0.026305,-0.003178,0.010598,-0.004502

In [43]:
# Concatetando a variavel TARGET ao Dataframe

dados = pd.concat([dados, TARGET], axis=1)

In [45]:
# Visualizando os dados

dados

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,TARGET
0,-1.274542,-0.375972,0.056829,0.439875,-0.039916,-0.114012,-0.054436,-0.033986,-0.000646,0.010634,...,-0.024860,-0.006067,0.001798,0.007291,0.010016,0.005148,0.003657,0.007141,-0.001370,0
1,-0.108038,0.048862,1.799190,-0.203618,-1.327840,0.274607,-0.164000,-0.164823,-0.081474,0.063830,...,-0.003157,0.044331,0.056909,-0.159439,-0.504883,-0.047619,-0.008906,0.002499,-0.061272,0
2,0.027935,0.439468,-0.335930,0.187874,-0.066789,0.081755,0.507333,0.414996,-0.005015,0.008462,...,0.007580,-0.040357,-0.002682,-0.011075,-0.002493,-0.029984,-0.005791,-0.002757,0.001031,0
3,1.427146,-1.492291,-0.688243,-0.024221,-0.671363,-0.843693,0.315254,-0.564295,-0.147847,0.076420,...,-0.024843,-0.007111,0.037683,-0.060107,0.012919,0.002226,0.009852,0.023860,0.053124,0
4,0.426464,-0.122872,1.311621,-0.190963,1.681094,-0.904324,-0.185651,0.363184,0.333842,0.352784,...,-0.216911,-0.019962,-0.105300,0.035171,-0.034816,-0.123019,-0.030567,-0.023965,-0.146107,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,-1.270342,-0.384579,0.077956,0.434298,-0.040857,-0.122725,-0.059527,-0.033157,0.000090,-0.001155,...,0.048869,0.030113,0.009766,0.015330,-0.008339,0.039176,0.005429,-0.011165,-0.010873,0
76016,-0.067651,-0.107534,1.304143,-0.150065,1.499899,-0.711709,0.512463,-0.583195,-0.217852,0.031439,...,-0.059266,0.041080,-0.094139,-0.096449,-0.000639,-0.129334,-0.023916,0.008731,0.058832,0
76017,-0.106216,0.347587,-0.295098,0.193288,-0.058630,0.067681,0.449450,0.385103,-0.045226,-0.009913,...,-0.024279,-0.023142,-0.007811,-0.015846,-0.002677,-0.047196,-0.004840,0.007015,0.002311,0
76018,0.048572,0.431814,-0.295902,0.319859,-0.060865,0.079397,0.497929,0.390067,0.008229,-0.010310,...,-0.022326,0.016797,-0.002666,0.003534,-0.000374,-0.017345,-0.000675,-0.002458,-0.004372,0
76019,-1.270678,-0.383891,0.076267,0.434744,-0.040782,-0.122028,-0.059120,-0.033223,0.000030,-0.000214,...,0.042971,0.027216,0.009126,0.014687,-0.006867,0.036453,0.005287,-0.009701,-0.010115,0

In [ ]:
# Dados de Treino e de Teste
# essa é uma outra forma de fazer treino e teste

dados_treino = dados.sample(frac=0.60, random_state=0)
dados_teste = dados.drop(dados_treino.index)

In [83]:
# Gerando as variaveis preditoras e variavel target

x_treino = dados_treino.iloc[:,0:30]
y_treino = dados_treino.iloc[:,30:31]

x_teste = dados_teste.iloc[:,0:30]
y_teste = dados_teste.iloc[:,30:31]

In [51]:
# Contagem dos dados

dados_treino.count()

0         45612
1         45612
2         45612
3         45612
4         45612
5         45612
6         45612
7         45612
8         45612
9         45612
10        45612
11        45612
12        45612
13        45612
14        45612
15        45612
16        45612
17        45612
18        45612
19        45612
20        45612
21        45612
22        45612
23        45612
24        45612
25        45612
26        45612
27        45612
28        45612
29        45612
TARGET    45612
dtype: int64

In [53]:
# Contagem dos dados

dados_teste.count()

0         30408
1         30408
2         30408
3         30408
4         30408
5         30408
6         30408
7         30408
8         30408
9         30408
10        30408
11        30408
12        30408
13        30408
14        30408
15        30408
16        30408
17        30408
18        30408
19        30408
20        30408
21        30408
22        30408
23        30408
24        30408
25        30408
26        30408
27        30408
28        30408
29        30408
TARGET    30408
dtype: int64

In [55]:
# Classificador Random Forest
classificador = RandomForestClassifier(max_depth=5, random_state=0)
classificador.fit(x_treino, y_treino)

# Executando as previsões
previsoes = classificador.predict(x_teste)

C:\Users\Pichau\anaconda3\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

In [57]:
# Avaliando a Confusion Matrix e a Acuracia

print('Acuracia: %s' % accuracy_score(y_teste, previsoes))

Acuracia: 0.9607340173638517